/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PlanificationRouteImport } from './routes/planification'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as ChambresRouteImport } from './routes/chambres'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificationRoute = PlanificationRouteImport.update({
  id: '/planification',
  path: '/planification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambresRoute = ChambresRouteImport.update({
  id: '/chambres',
  path: '/chambres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chambres': typeof ChambresRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/planification': typeof PlanificationRoute
  '/stats': typeof StatsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chambres': typeof ChambresRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/planification': typeof PlanificationRoute
  '/stats': typeof StatsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chambres': typeof ChambresRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/planification': typeof PlanificationRoute
  '/stats': typeof StatsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chambres'
    | '/historique'
    | '/login'
    | '/planification'
    | '/stats'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chambres'
    | '/historique'
    | '/login'
    | '/planification'
    | '/stats'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chambres'
    | '/historique'
    | '/login'
    | '/planification'
    | '/stats'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChambresRoute: typeof ChambresRoute
  HistoriqueRoute: typeof HistoriqueRoute
  LoginRoute: typeof LoginRoute
  PlanificationRoute: typeof PlanificationRoute
  StatsRoute: typeof StatsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planification': {
      id: '/planification'
      path: '/planification'
      fullPath: '/planification'
      preLoaderRoute: typeof PlanificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambres': {
      id: '/chambres'
      path: '/chambres'
      fullPath: '/chambres'
      preLoaderRoute: typeof ChambresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChambresRoute: ChambresRoute,
  HistoriqueRoute: HistoriqueRoute,
  LoginRoute: LoginRoute,
  PlanificationRoute: PlanificationRoute,
  StatsRoute: StatsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
